---
abstract: 'Check the moves of a game of Go for rule violations.'
author:
  - 'DG <deg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Go-Referee
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  English: 0
  Games::Go::SGF: 0
  IO::File: 0
  Test::More: 0
version: 0.09
